# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ArchiveDB
spring.datasource.username=postgres
spring.datasource.password=123

# File paths (Linux server)
file.upload.dir=/home/supremcourt/uploads/scanned-documents
spring.file.directory=/home/supremcourt/uploads
scanner.folder.path=/home/supremcourt/ScannerOutput

# Frontend (server IP)
frontend.url=http://103.132.98.175

# Less logs on server
logging.level.org.springframework.security=WARN
logging.level.com.MCIT.ArchiveManagementSystem=INFO
logging.level.com.MCIT.ArchiveManagementSystem.security.jwt=WARN