# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ArchiveDB
spring.datasource.username=postgres
spring.datasource.password=123

# File paths (Windows)
file.upload.dir=uploads/scanned-documents
spring.file.directory=C:/uploads
scanner.folder.path=C:/ScannerOutput

# Frontend (local React)
frontend.url=http://localhost:3000

# Show all logs locally
logging.level.org.springframework.security=DEBUG
logging.level.com.MCIT.ArchiveManagementSystem=DEBUG
logging.level.com.MCIT.ArchiveManagementSystem.security.jwt=DEBUG