export const addHazariTexts = (t) => ({
  back: t("back"),
  addNewHazari: t("addNewHazari"),

  scannerFolder: t("scannerFolder"),
  noFiles: t("noFiles"),
  scan: t("scan"),
  scanning: t("scanning"),
  loadFiles: t("loadFiles"),
  scannerFiles: t("scannerFiles"),
  manualUpload: t("manualUpload"),
  readyToUpload: t("readyToUpload"),

  recordType: t("recordType"),
  indraj: t("indraj"),
  hazari: t("hazari"),
  type: t("type"),
  subType: t("subType"),
  selectTypeFirst: t("selectTypeFirst"),
  year: t("year"),
  org: t("org"),
  description: t("description"),

  cancel: t("cancel"),
  save: t("save"),
  saving: t("saving"),
  loading: t("loading"),

  requiredFieldsError: t("requiredFieldsError"),
  filesFound: (count) => t("filesFound", { count }),
  noFilesFound: t("noFilesFound"),
  scanError: t("scanError"),
  loadFilesError: t("loadFilesError"),
  loadTypesOrgsError: t("loadTypesOrgsError"),
  loadSubTypesError: t("loadSubTypesError"),
});
